swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'

host: localhost:3001
basePath: /api/v1
schemes:
  - http

paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
       # - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /transactions:
    get:
      security:
        - Bearer: []
      tags:
        - User Transactions
      summary: All transaction by user
      description: Return all transactions on the month and all accounts
      parameters:
        - name: month
          in: query
          description: Le mois au format AAAA-MM (par exemple, 2024-09)
          required: true
          type: string
          format: date
      responses:
        '200':
          description: Successful operation
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                  example: 1
                compte:
                  type: string
                  example: "A"
                date:
                  type: string
                  example: "2024-09-17"
                montant:
                  type: number
                  format: float
                  example: 100.0
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Account not found
        '500':
          description: Internal Server Error

  /accounts/{accountId}/transactions/{transactionId}:
    parameters:
      - name: accountId
        in: path
        required: true
        type: string
      - name: transactionId
        in: path
        required: true
        type: string
    get:
      security:
        - Bearer: []
      tags:
        - User Transactions
      summary: Find transaction by ID
      description: Return transaction by ID
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/AccountTransaction'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Account not found
        '500':
          description: Internal Server Error

  /accounts/{accountId}/transactions/{transactionId}/category:
    parameters:
      - name: accountId
        in: path
        required: true
        type: string
      - name: transactionId
        in: path
        required: true
        type: string
    post:
      security:
        - Bearer: []
      tags:
        - User Transactions
      summary: Add new comment
      description: Add new comment on 'category'
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/TransactionCategory'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Account not found
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Transactions
      summary: Change category
      description: Change comment on 'category'
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/TransactionCategory'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Account not found
        '500':
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - User Transactions
      summary: Delete category
      description: Delete comment on 'category'
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/TransactionCategory'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Account not found
        '500':
          description: Internal Server Error

  /accounts/{accountId}/transactions/{transactionId}/note:
    parameters:
      - name: accountId
        in: path
        required: true
        type: string
      - name: transactionId
        in: path
        required: true
        type: string
    post:
      security:
        - Bearer: []
      tags:
        - User Transactions
      summary: Add new note
      description: Add new comment on 'note'
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/TransactionNote'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Account not found
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Transactions
      summary: Change note
      description: Change comment on 'note'
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/TransactionNote'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Account not found
        '500':
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - User Transactions
      summary: Delete note
      description: Delete comment on 'note'
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/TransactionNote'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Account not found
        '500':
          description: Internal Server Error
    
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  UserAccount:
    type: object
    properties:
      id:
        type: string
      account:
        type: string
        description: account name
      sum: 
        type: float
  AccountTransaction:
    type: object
    properties: 
      id: 
        type: string
      date: 
        type: string
        description: transaction date 
      description:
        type: string
        description: transaction description 
      amount: 
        type: float
        description: transaction amount
      balance:
        type: float
        description: transaction balance 
      transactionType:
        type: string
        description: transaction type 
      category:
        type: string
        description: transaction category
      note:
        type: string
        description: transaction note
  TransactionCategory:
    type: object
    properties:
      category: 
        type: string
  TransactionNote:
    type: object
    properties:
      note:
        type: string
